// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rfid.Infrastructure.Persistence;

#nullable disable

namespace Rfid.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914205301_RoadmapV12")]
    partial class RoadmapV12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rfid")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rfid.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status", "RaisedAt");

                    b.ToTable("alerts", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Antenna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PathLossExponent")
                        .HasColumnType("double precision");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<double?>("PowerDbm")
                        .HasColumnType("double precision");

                    b.Property<double?>("RssiAt1m")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<double?>("X")
                        .HasColumnType("double precision");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("DeviceId", "Port")
                        .IsUnique();

                    b.ToTable("antennas", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("SiteLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("devices", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.IntegrationEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlertCursor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApiToken")
                        .HasColumnType("text");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeliveredCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EventCursor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IncludeAlerts")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Mapping")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<string>("Secret")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("integration_endpoints", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustodianPartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("CycleCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueBackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastInspectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastSeenDeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastSeenLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextInspectionDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentItemId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PositionAccuracyM")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("PositionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PositionLocationId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double?>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("PurchasedAt")
                        .HasColumnType("date");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("CustodianPartyId");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("NextInspectionDue");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("TenantId", "CurrentLocationId");

                    b.HasIndex("TenantId", "Identifier")
                        .IsUnique();

                    b.HasIndex("TenantId", "ItemTypeId", "State");

                    b.ToTable("items", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.ItemEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromPartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromState")
                        .HasColumnType("text");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ToPartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToState")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "OccurredAt")
                        .IsDescending(false, true);

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("item_events", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.ItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeSchema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("InspectionIntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsContainer")
                        .HasColumnType("boolean");

                    b.Property<string>("LabelDesign")
                        .HasColumnType("text");

                    b.Property<string>("LabelTemplate")
                        .HasColumnType("text");

                    b.Property<string>("Lifecycle")
                        .HasColumnType("jsonb");

                    b.Property<int?>("MaxCycles")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ReorderPoint")
                        .HasColumnType("numeric");

                    b.Property<bool>("RequiresInspection")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TracksCycles")
                        .HasColumnType("boolean");

                    b.Property<bool>("TracksExpiry")
                        .HasColumnType("boolean");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<int?>("UsefulLifeMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Vertical")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("item_types", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMobile")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId", "Code");

                    b.HasIndex("TenantId", "Path");

                    b.ToTable("locations", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ContainerItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DueBackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetState")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Reference");

                    b.HasIndex("TenantId", "StartedAt");

                    b.ToTable("operations", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.OperationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Epc")
                        .HasColumnType("text");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OperationId");

                    b.ToTable("operation_lines", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code");

                    b.ToTable("parties", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.PresenceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<double?>("LastRssi")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PeakRssi")
                        .HasColumnType("double precision");

                    b.Property<int>("ReadCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("TenantId", "ItemId", "ExitedAt");

                    b.HasIndex("TenantId", "LocationId", "ExitedAt");

                    b.ToTable("presence_sessions", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vertical")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("rules", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.SolutionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vertical")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("solution_templates", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Stocktake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpectedCount")
                        .HasColumnType("integer");

                    b.Property<int>("FoundCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("MissingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnexpectedCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("stocktakes", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.StocktakeLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Epc")
                        .HasColumnType("text");

                    b.Property<bool>("Expected")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FoundLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StocktakeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StocktakeId", "ItemId");

                    b.ToTable("stocktake_lines", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.StocktakeSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AutoReconcileHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastStocktakeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("TimeOfDay")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Enabled", "NextRunAt");

                    b.ToTable("stocktake_schedules", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EncodedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Epc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("Tid");

                    b.HasIndex("TenantId", "Epc")
                        .IsUnique();

                    b.ToTable("tags", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.TagRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AntennaPort")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Epc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Rssi")
                        .HasColumnType("double precision");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReadAt");

                    b.HasIndex("TenantId", "Epc", "ReadAt");

                    b.ToTable("tag_reads", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tenants", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("users", "rfid");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Antenna", b =>
                {
                    b.HasOne("Rfid.Domain.Entities.Device", "Device")
                        .WithMany("Antennas")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rfid.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Item", b =>
                {
                    b.HasOne("Rfid.Domain.Entities.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Rfid.Domain.Entities.Party", "CustodianParty")
                        .WithMany()
                        .HasForeignKey("CustodianPartyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Rfid.Domain.Entities.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rfid.Domain.Entities.Item", "ParentItem")
                        .WithMany()
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentLocation");

                    b.Navigation("CustodianParty");

                    b.Navigation("ItemType");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Location", b =>
                {
                    b.HasOne("Rfid.Domain.Entities.Location", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.OperationLine", b =>
                {
                    b.HasOne("Rfid.Domain.Entities.Operation", null)
                        .WithMany("Lines")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rfid.Domain.Entities.StocktakeLine", b =>
                {
                    b.HasOne("Rfid.Domain.Entities.Stocktake", null)
                        .WithMany("Lines")
                        .HasForeignKey("StocktakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Rfid.Domain.Entities.Item", "Item")
                        .WithMany("Tags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Device", b =>
                {
                    b.Navigation("Antennas");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Item", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Operation", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Rfid.Domain.Entities.Stocktake", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
