import { createContext, useContext } from 'react';

export type Lang = 'en' | 'ms' | 'zh' | 'es' | 'de' | 'fr';
export const LANGS: { code: Lang; label: string }[] = [{ code: 'en', label: 'English' }, { code: 'ms', label: 'Bahasa Melayu' }, { code: 'zh', label: '中文' }, { code: 'es', label: 'Español' }, { code: 'de', label: 'Deutsch' }, { code: 'fr', label: 'Français' }];

/** Keys fall back to English text when a language has no entry, so partial translations stay usable. */
const dict: Record<Lang, Record<string, string>> = {
  en: {},
  ms: { 'RFID Handheld': 'Pengimbas RFID', 'Scan / Inventory': 'Imbas / Inventori', 'Lookup': 'Cari', 'Locate': 'Kesan', 'Stocktake': 'Kiraan stok', 'Operations': 'Operasi', 'Commission': 'Daftar tag', 'Floor plan': 'Pelan lantai', 'Map & geofences': 'Peta & geopagar', 'Settings': 'Tetapan', 'Sign in': 'Log masuk', 'Sign out': 'Log keluar', 'Sync now': 'Segerak sekarang', 'Language': 'Bahasa', 'Offline data': 'Data luar talian', 'Download for offline': 'Muat turun untuk luar talian', 'Clear cache': 'Kosongkan cache', 'GPS': 'GPS', 'Attach GPS position to scans and operations': 'Lampirkan kedudukan GPS pada imbasan dan operasi', 'Inside fence': 'Di dalam geopagar', 'Outside all fences': 'Di luar semua geopagar', 'Refresh': 'Muat semula', 'Working…': 'Sedang diproses…', 'Read everything in range, see what it is': 'Baca semua dalam jarak, lihat apa itu', 'Identify one tag, history, quick actions': 'Kenal pasti satu tag, sejarah, tindakan pantas', 'Geiger-counter search for a specific item': 'Cari item tertentu (gaya Geiger)', 'Count a location: found / missing / unexpected': 'Kira lokasi: ditemui / hilang / tidak dijangka', 'Receive · Transfer · Issue · Return · Dispatch · Stage…': 'Terima · Pindah · Keluar · Pulang · Hantar · Peringkat…', 'Bind / encode tags to new items': 'Ikat / kod tag kepada item baharu', 'Anchors and live positions · works offline from the last sync': 'Sauh dan kedudukan langsung · berfungsi luar talian', 'Your position against geofences · restricted-zone warnings': 'Kedudukan anda berbanding geopagar · amaran zon larangan' },
  zh: { 'RFID Handheld': 'RFID 手持终端', 'Scan / Inventory': '扫描 / 盘点', 'Lookup': '查询', 'Locate': '定位', 'Stocktake': '库存盘点', 'Operations': '作业', 'Commission': '标签绑定', 'Floor plan': '平面图', 'Map & geofences': '地图与围栏', 'Settings': '设置', 'Sign in': '登录', 'Sign out': '退出', 'Sync now': '立即同步', 'Language': '语言', 'Offline data': '离线数据', 'Download for offline': '下载离线数据', 'Clear cache': '清除缓存', 'GPS': 'GPS', 'Attach GPS position to scans and operations': '为扫描和作业附加 GPS 位置', 'Inside fence': '在围栏内', 'Outside all fences': '不在任何围栏内', 'Refresh': '刷新', 'Working…': '处理中…', 'Read everything in range, see what it is': '读取范围内的所有标签', 'Identify one tag, history, quick actions': '识别单个标签、历史与快捷操作', 'Geiger-counter search for a specific item': '盖革计数式寻找指定物品', 'Count a location: found / missing / unexpected': '盘点位置：已找到 / 缺失 / 意外', 'Receive · Transfer · Issue · Return · Dispatch · Stage…': '收货 · 转移 · 发放 · 归还 · 发运 · 工序…', 'Bind / encode tags to new items': '为新物品绑定 / 写入标签', 'Anchors and live positions · works offline from the last sync': '锚点与实时位置 · 支持离线', 'Your position against geofences · restricted-zone warnings': '您与地理围栏的位置 · 禁区警告' },
  es: { 'RFID Handheld': 'Terminal RFID', 'Scan / Inventory': 'Escanear / Inventario', 'Lookup': 'Buscar', 'Locate': 'Localizar', 'Stocktake': 'Recuento', 'Operations': 'Operaciones', 'Commission': 'Alta de etiquetas', 'Floor plan': 'Plano', 'Map & geofences': 'Mapa y geocercas', 'Settings': 'Ajustes', 'Sign in': 'Iniciar sesión', 'Sign out': 'Cerrar sesión', 'Sync now': 'Sincronizar ahora', 'Language': 'Idioma', 'Offline data': 'Datos sin conexión', 'Download for offline': 'Descargar para uso sin conexión', 'Clear cache': 'Borrar caché', 'Attach GPS position to scans and operations': 'Adjuntar posición GPS a escaneos y operaciones', 'Inside fence': 'Dentro de la geocerca', 'Outside all fences': 'Fuera de todas las geocercas', 'Refresh': 'Actualizar', 'Working…': 'Procesando…' },
  de: { 'RFID Handheld': 'RFID-Handgerät', 'Scan / Inventory': 'Scannen / Inventur', 'Lookup': 'Nachschlagen', 'Locate': 'Orten', 'Stocktake': 'Bestandsaufnahme', 'Operations': 'Vorgänge', 'Commission': 'Tags anlegen', 'Floor plan': 'Grundriss', 'Map & geofences': 'Karte & Geofences', 'Settings': 'Einstellungen', 'Sign in': 'Anmelden', 'Sign out': 'Abmelden', 'Sync now': 'Jetzt synchronisieren', 'Language': 'Sprache', 'Offline data': 'Offline-Daten', 'Download for offline': 'Für offline herunterladen', 'Clear cache': 'Cache leeren', 'Attach GPS position to scans and operations': 'GPS-Position an Scans und Vorgänge anhängen', 'Inside fence': 'Innerhalb des Geofence', 'Outside all fences': 'Außerhalb aller Geofences', 'Refresh': 'Aktualisieren', 'Working…': 'Wird verarbeitet…' },
  fr: { 'RFID Handheld': 'Terminal RFID', 'Scan / Inventory': 'Scanner / Inventaire', 'Lookup': 'Rechercher', 'Locate': 'Localiser', 'Stocktake': 'Comptage', 'Operations': 'Opérations', 'Commission': 'Enrôler des tags', 'Floor plan': 'Plan', 'Map & geofences': 'Carte et géorepères', 'Settings': 'Paramètres', 'Sign in': 'Connexion', 'Sign out': 'Déconnexion', 'Sync now': 'Synchroniser', 'Language': 'Langue', 'Offline data': 'Données hors ligne', 'Download for offline': 'Télécharger pour le hors ligne', 'Clear cache': 'Vider le cache', 'Attach GPS position to scans and operations': 'Joindre la position GPS aux scans et opérations', 'Inside fence': 'Dans le géorepère', 'Outside all fences': 'Hors de tous les géorepères', 'Refresh': 'Actualiser', 'Working…': 'Traitement…' },
};

export const translate = (lang: Lang, text: string) => dict[lang]?.[text] ?? text;
export const LangContext = createContext<Lang>('en');
export function useT() { const lang = useContext(LangContext); return (text: string) => translate(lang, text); }
